### ISSUE TITLE
tokenizing with regex

### ISSUE THREAD

**Issue by njyjn** [njyjn/ARIADNE#1]
_From @darrenwee on May 23, 2016 3:55_

We can start refactoring some code to use regex for tokenizing rather than enforcing underscores-for-spaces on the user-end. 

For example, suppose I want to start as a user `John Doe Xiao Ming` from `Black` house. The current implementation requires the user to tokenize on the bot's behalf, i.e. the command `/start John_Doe_Xiao_Ming Black` must be entered.

We can refactor such parts of the code to use regular expressions to perform the tokenizing instead. Using the same example as above, we can replace lines [lines 538 to 548](https://github.com/njyjn/ARIADNE/blob/master/main.py#L538-L548) to the following example:

````python
import re # regular expression module

# the message received from the API
message = '/start John Doe Xiao Ming Black'

# make the regex pattern for this command
start_re = re.compile('(/start)\s+([a-z\s]+)\s+(green|black|purple|blue|red|orange)', re.IGNORECASE)

# perform matching
start_tokens = re.match(start_re, command)

register(chat_id, start_tokens.group(2), start_tokens.group(3) + ':')
````

This will then enable you to enter commands without having to substitute underscores for spaces. We can do the same for other parts of the bot, e.g. `/key` and `/answer` for `withinus.py`. It should also reduce user error because of sloppy typing and enable you to sanitize inputs (e.g. the pattern looks for either `green`, `black`, `purple`, `blue`, `red`, and `orange` as the last word and fails to match if otherwise).

If it looks too sloppy to enter `/start John Doe Xiao Ming Black`, then we can add single/double quotes to help the user "chunk" the parameters, i.e. `/start 'John Doe Xiao Ming' 'Black'` and do the same in the regex pattern.

A further enhancement to `/key` and `/answer` would be to use fuzzy string matching to match close but not exact answers with the `fuzzywuzzy` module, but that can be a separate item on the to-do list.

Sounds good?

_Copied from original issue: njyjn/ARIADNEfork#3_

**Comment by njyjn** [comment]
Sounds good, Darren.

**Comment by njyjn** [comment]
Let's implement the regex functionality for /start first.

**Comment by njyjn** [comment]
_From @darrenwee on May 23, 2016 7:53_

Okay! Do you wanna do it or should I? You can use the pattern above in `start_re` and it should be sufficient. If `re.match` fails, i.e. the input is not in the right format, then `start_token` will be a `None` type object.

**Comment by njyjn** [comment]
I'll give it a try and let you know if I encounter anything. Thanks!

**Comment by darrenwee** [comment]
Have you tested this code yet? Try with very long names with lots of spaces, or invalid house names. It should fail to add invalid commands. You may also want to implement an error message for the user if the add fails (make it idiot-proof).

**Comment by njyjn** [comment]
In progress...

**Comment by njyjn** [comment]
Tested with 

1. /start: Start command helper invoked
2. /start LOREM IPSUM SIT DOLOR AMET: Wrong start command helper invoked. 
3. /start LOREM IPSUM SIT DOLOR AMET PURPLE: Success
4. /start LOREM IPSUM PURPLE SIT DOLOR AMET: "SIT DOLOR AMET" ignored. 

Personally don't see an issue with (4), only if freshies are trying to be playful. Or unless we have a freshie with last name BLACK. Anyway, we are using OG names instead of colors, and it's unlikely that someone has a last name corresponding to the OG name.

**Comment by darrenwee** [comment]
For case (4), we should implement a more helpful error message like "Invalid house." instead of ignoring the command.

If we have a freshie with a color/one of the OG names for their last name, it shouldn't be a problem. The correct command entry should trail with the house/OG name anyway. `/start SIRIUS BLACK BLACK` is a valid command to add `sirius black` to `black` house. Likewise for OG names, i.e. `/start sirius nox nox` adds `sirius nox` to `nox` house.

Have you rolled this out to other commands other than `/start`? If not, we can start a branch to implement regex for any remaining relevant commands.

**Comment by njyjn** [comment]
`/start Justin Black Black Black` creates a user `Justin Black Black` from `Black` house. So the tokenizing works.

I can edit the error message to show what would be shown when `/start` is pressed, ie: 

```
Enter "/start Full Name OG" into terminal.
eg: /start Justin Ng Aether'
```

**Comment by darrenwee** [comment]
Yes, that would be more helpful. Perhaps you can use the `help` module inside the repository to house all the error messages and help docs to make it more user-friendly. I do this for my [`voglbot` here](https://github.com/darrenwee/voglbot/blob/class-based/helper.py). If you think this is good to add, we can open another branch and issue to discuss this.
