### ISSUE TITLE
proto branch and protobot deploy

### ISSUE THREAD

**Issue by njyjn** [njyjn/ARIADNE#6]
Currently only master is being deployed to ARIADNEbot manually, from a local path. 

We plan to create a proto branch and deploy it to ARIADNEprotobot. However, Google no longer supports github push to deploy. So we need to manually copy modified files over to a separate local path for protobot. Is a cron job possible?

**Comment by darrenwee** [comment]
See https://cloud.google.com/docs/permissions-overview#continuous-integration

We can use continuous integration tools like Jenkins to deploy updates whenever a commit to the `master` branch is made. We can piggyback on the server I use for VOGLBot to host a Jenkins server.  Lemme look at the documentation to see how to use it.

**Comment by darrenwee** [comment]
https://github.com/integrations/travis-ci

Try this. It supports continuous integration to Google App Engine. You'll have to do it because I'm not very familiar with GAE.

**Comment by njyjn** [comment]
Done. Testing now.

**Comment by darrenwee** [comment]
We can use Travis for the protobot for now since we are only testing, so we can ignore the token problem. Is it possible to spawn 2 instances of Travis to deploy to both bots?

**Comment by njyjn** [comment]
We'll have to manually update the application name in app.yaml if we **deploy** to main, and revert when **pushing** to protobot.

Now these are the two errors I get when Travis tries to deploy to GAE:

> ERROR: (gcloud.config.set) Section "app" has no property "use_cloud_build".

> ERROR: (gcloud.preview.app.deploy) Docker builds now use Container Builder by default. To run a Docker build on
> your own host, you can run:
>     docker build -t gcr.io/<project>/<service.version> .
>     gcloud docker push gcr.io/<project>/<service.version>
>     gcloud preview app deploy --image-url=gcr.io/<project>/<service.version>
>     
> Deployment failed.

**Comment by njyjn** [comment]
Ok I found out that by changing the name of the app in app.yaml app engine will just deploy it there. So that's a quick workaround to deploy to protobot.
