### ISSUE TITLE
ARIADNE easter response not returning

### ISSUE THREAD

**Issue by darrenwee** [njyjn/ARIADNE#8]
It seems `ARIADNE` is not working properly? Easter egg responses are not being returned for certain terms (`bye`, `vulgar`, `question`) but is working for `morning` and `/start`. Is it possible to paste the python traceback here?

**Comment by njyjn** [comment]
This is the error:

> 14:56:00.083
> request body: (/base/data/home/apps/s~ariadnebot1/1.393041661775819277/main.py:148)
> 14:56:00.083
> {u'message': {u'date': 1464243286, u'text': u'Can', u'from': {u'username': u'ohdearren', u'first_name': u'Darren', u'id': 53558212}, u'message_id': 12080, u'chat': {u'username': u'ohdearren', u'first_name': u'Darren', u'type': u'private', u'id': 53558212}}, u'update_id': 7429635} (/base/data/home/apps/s~ariadnebot1/1.393041661775819277/main.py:149)
> 14:56:00.123
> 'list' object has no attribute 'encode' (/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py:1552)
> Traceback (most recent call last):
>   File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
>     rv = self.handle_exception(request, response, e)
>   File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
>     rv = self.router.dispatch(request, response)
>   File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
>     return route.handler_adapter(request, response)
>   File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
>     return handler.dispatch()
>   File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
>     return self.handle_exception(e, self.app.debug)
>   File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
>     return method(*args, **kwargs)
>   File "/base/data/home/apps/s~ariadnebot1/1.393041661775819277/main.py", line 529, in post
>     reply(easter.responseHandler(text, str(getKey(chat_id).name).replace('_',' ').title(), adminFlag))
>   File "/base/data/home/apps/s~ariadnebot1/1.393041661775819277/main.py", line 204, in reply
>     'text': msg.encode('utf-8'),
> AttributeError: 'list' object has no attribute 'encode'

'encode' is found in the reply method, which takes in a string and encodes it to UTF-8. Apparently `responseHandler` in `easter.py` is returning a list, therefore reply in `main.py` cannot encode it.

**Comment by njyjn** [comment]
This is where the error occurs: 

def responseHandler(text, name, adminFlag):
    # ============ exact trigger term matches ===========
    if easter.has_key(text):
        **return easter.get(text)**

    # ============ fuzzy match trigger terms ============
    ### for matching to something close to the actual key word ###
    elif getClosestTerm(text) is not None:
        **return easter.get(getClosestTerm(text))**

Since this returns the list literal and does not call the `getRandom...` method.

**Comment by darrenwee** [comment]
Okay, I got it now. This is what I get for not properly testing the code haha. I have fixed it here https://github.com/njyjn/ARIADNE/issues/9. Carry on further discussion if any at the pull request thread.
